# permissions for end users to view nodequotaconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodequotaconfig-viewer-role
rules:
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs/status
  verbs:
  - get
