---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - namespace
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
