apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hns-nqs-plugin.fullname" . }}-manager-rolebinding
  labels:
  {{- include "hns-nqs-plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hns-nqs-plugin.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hns-nqs-plugin.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}