apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hns-nqs-plugin.fullname" . }}-manager-role
  labels:
  {{- include "hns-nqs-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - dana.hns.io
  resources:
  - nodequotaconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dana.hns.io
  resources:
  - subnamespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch