apiVersion: v1
kind: Service
metadata:
  name: {{ include "hns-nqs-plugin.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "hns-nqs-plugin.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.httpsPort }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    control-plane: controller-manager