apiVersion: dana.hns.io/v1alpha1
kind: NodeQuotaConfig
metadata:
  name: example-nodequotaconfig
spec:
  reservedHoursToLive: 24
  controlledResources: ["cpu","ephermal-storage","memory","pods","nvidia.com/gpu"]
  subnamespacesRoots:
    - rootNamespace: ocp-asaf-the-doctor
      secondaryRoots:
        - labelSelector:
            app: sahar
          name: sahar
          multipliers:
            cpu: "2"
            memory: "2"
        - labelSelector:
            app: omer
          name: omer
          multipliers:
            memory: "4"