name: pre-merge
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=2m
      - name: Run tests
        run: make test